#!/bin/bash

arr=(rpi01 rpi02 rpi03 rpi04 rpi05 rpi06 rpi07 rpi08 rpi09 rpi10 rpi11 rpi12 rpi13 rpi14 rpi15 rpi16 rpi17 rpi18)

for word in ${arr[@]}; do

ping -c 1 -W 1 $word > /dev/null

if [ $? == 0 ]; then
echo $word" : ALIVE"
else echo $word" : DEAD"

fi

done

#This is a comment
